/**
 * Configuration PDF générée automatiquement
 * Généré le: 2025-12-20T15:54:19.999Z
 * Ne pas modifier manuellement - utiliser scripts/generate-pdf-config.js
 */

export interface PDFFieldConfig {
  key: string;
  label: string;
  type: "string" | "number" | "boolean" | "date" | "array" | "enum";
  required: boolean;
}

export interface PDFSectionConfig {
  title: string;
  fields: string[];
  layout: "list" | "grid";
}

export interface PDFPathologyConfig {
  sections: Record<string, PDFSectionConfig>;
}

export const PDF_CONFIG: Record<string, PDFPathologyConfig> = {
  asthma: {
    sections: {
      consultation: {
        title: "Motif de consultation",
        fields: [],
        layout: "list",
      },
      medicalHistory: {
        title: "Antécédents médicaux",
        fields: [],
        layout: "list",
      },
      diseaseHistory: {
        title: "Histoire de la maladie",
        fields: [],
        layout: "list",
      },
      generalState: {
        title: "État général",
        fields: [],
        layout: "list",
      },
      respiratorySystem: {
        title: "Appareil respiratoire",
        fields: [],
        layout: "list",
      },
      cardiovascularSystem: {
        title: "Appareil cardiovasculaire",
        fields: [],
        layout: "list",
      },
      digestiveSystem: {
        title: "Appareil digestif",
        fields: [],
        layout: "list",
      },
      urinarySystem: {
        title: "Appareil urinaire",
        fields: [],
        layout: "list",
      },
      musculoskeletalSystem: {
        title: "Appareil musculo-squelettique",
        fields: [],
        layout: "list",
      },
      nervousSystem: {
        title: "Système nerveux",
        fields: [],
        layout: "list",
      },
      skinMucous: {
        title: "Peau et muqueuses",
        fields: [],
        layout: "list",
      },
      orlEyesMouth: {
        title: "ORL, yeux, bouche",
        fields: [],
        layout: "list",
      },
      complementaryExams: {
        title: "Examens complémentaires",
        fields: [],
        layout: "grid",
      },
      severityClassification: {
        title: "Classification de sévérité",
        fields: [],
        layout: "list",
      },
      treatment: {
        title: "Traitement",
        fields: [],
        layout: "list",
      },
      followUp: {
        title: "Suivi",
        fields: [],
        layout: "list",
      },
    },
  },
  bpco: {
    sections: {
      consultation: {
        title: "Motif de consultation",
        fields: [],
        layout: "list",
      },
      comorbidities: {
        title: "Comorbidités",
        fields: [],
        layout: "list",
      },
      personalHistory: {
        title: "Antécédents personnels",
        fields: [],
        layout: "list",
      },
      recentContagion: {
        title: "Contage récent",
        fields: [],
        layout: "list",
      },
      toxicHabits: {
        title: "Habitudes toxiques",
        fields: [],
        layout: "list",
      },
      generalSigns: {
        title: "Signes généraux",
        fields: [],
        layout: "list",
      },
      functionalSigns: {
        title: "Signes fonctionnels",
        fields: [],
        layout: "list",
      },
      clinicalExam: {
        title: "Examen clinique",
        fields: [],
        layout: "grid",
      },
      chestXRay: {
        title: "Radiographie thoracique",
        fields: [],
        layout: "list",
      },
      sputumBacteriology: {
        title: "Bactériologie des expectorations",
        fields: [],
        layout: "list",
      },
      genetics: {
        title: "Génétique BK",
        fields: [],
        layout: "list",
      },
      biology: {
        title: "Biologie",
        fields: [],
        layout: "grid",
      },
      otherAssessments: {
        title: "Autres bilans",
        fields: [],
        layout: "list",
      },
      prescribedTreatment: {
        title: "Traitement prescrit",
        fields: [],
        layout: "list",
      },
      serumDosage: {
        title: "Dosage sérique",
        fields: [],
        layout: "list",
      },
      evolution: {
        title: "Évolution",
        fields: [],
        layout: "list",
      },
      dischargeConclusion: {
        title: "Conclusion de sortie",
        fields: [],
        layout: "list",
      },
    },
  },
  ddb: {
    sections: {
      consultation: {
        title: "Motif de consultation",
        fields: [],
        layout: "list",
      },
      medicalHistory: {
        title: "Antécédents médicaux",
        fields: [],
        layout: "list",
      },
      toxicHistory: {
        title: "Antécédents toxiques",
        fields: [],
        layout: "list",
      },
      diseaseHistory: {
        title: "Histoire de la maladie",
        fields: [],
        layout: "list",
      },
      respiratorySymptoms: {
        title: "Symptômes respiratoires",
        fields: [],
        layout: "list",
      },
      extraRespiratorySymptoms: {
        title: "Symptômes extra-respiratoires",
        fields: [],
        layout: "list",
      },
      physicalSigns: {
        title: "Signes physiques",
        fields: [],
        layout: "list",
      },
      complementaryExams: {
        title: "Examens complémentaires",
        fields: [],
        layout: "grid",
      },
      conclusion: {
        title: "Conclusion",
        fields: [],
        layout: "list",
      },
      etiology: {
        title: "Étiologie",
        fields: [],
        layout: "list",
      },
      treatment: {
        title: "Traitements envisagés",
        fields: [],
        layout: "list",
      },
      followUp: {
        title: "Suivi",
        fields: [],
        layout: "list",
      },
    },
  },
  tbk: {
    sections: {
      consultation: {
        title: "Motif d'hospitalisation",
        fields: [],
        layout: "list",
      },
      comorbidities: {
        title: "Comorbidités",
        fields: [],
        layout: "list",
      },
      personalHistory: {
        title: "ATCD personnels",
        fields: [],
        layout: "list",
      },
      recentContagion: {
        title: "Contage récent",
        fields: [],
        layout: "list",
      },
      toxicHabits: {
        title: "Habitudes toxiques",
        fields: [],
        layout: "list",
      },
      generalSigns: {
        title: "Signes généraux",
        fields: [],
        layout: "list",
      },
      functionalSigns: {
        title: "Signes fonctionnels",
        fields: [],
        layout: "list",
      },
      clinicalExam: {
        title: "Examen clinique",
        fields: [],
        layout: "grid",
      },
      chestXRay: {
        title: "Rx thoracique",
        fields: [],
        layout: "list",
      },
      sputumBacteriology: {
        title: "Bactériologie expectorations",
        fields: [],
        layout: "list",
      },
      bkGenetics: {
        title: "Génétique BK",
        fields: [],
        layout: "list",
      },
      biology: {
        title: "Biologie",
        fields: [],
        layout: "grid",
      },
      otherAssessments: {
        title: "Autres bilans",
        fields: [],
        layout: "list",
      },
      prescribedTreatment: {
        title: "Traitement prescrit",
        fields: [],
        layout: "list",
      },
      serumDosage: {
        title: "Dosage sérique AT",
        fields: [],
        layout: "list",
      },
      evolution: {
        title: "Évolution",
        fields: [],
        layout: "list",
      },
      dischargeConclusion: {
        title: "Conclusion de sortie",
        fields: [],
        layout: "list",
      },
    },
  },
  sleep: {
    sections: {
      consultation: {
        title: "Motif de consultation",
        fields: [],
        layout: "list",
      },
      medicalHistory: {
        title: "Antécédents médicaux",
        fields: [],
        layout: "list",
      },
      clinicalExam: {
        title: "Examen clinique",
        fields: [],
        layout: "grid",
      },
      orlExam: {
        title: "Examen ORL",
        fields: [],
        layout: "list",
      },
      complementaryExams: {
        title: "Examens complémentaires",
        fields: [],
        layout: "grid",
      },
      diagnosis: {
        title: "Diagnostic",
        fields: [],
        layout: "list",
      },
      treatment: {
        title: "Traitement",
        fields: [],
        layout: "list",
      },
      followUp: {
        title: "Suivi",
        fields: [],
        layout: "list",
      },
    },
  },
  pleuralEffusion: {
    sections: {
      consultation: {
        title: "Motif de consultation",
        fields: [],
        layout: "list",
      },
      medicalHistory: {
        title: "Antécédents médicaux",
        fields: [],
        layout: "list",
      },
      biology: {
        title: "Biologie",
        fields: [],
        layout: "grid",
      },
      chestXRay: {
        title: "Radiographie thoracique",
        fields: [],
        layout: "list",
      },
      clinicalExam: {
        title: "Examen clinique",
        fields: [],
        layout: "grid",
      },
      diagnosis: {
        title: "Diagnostic",
        fields: [],
        layout: "list",
      },
      evolution: {
        title: "Évolution",
        fields: [],
        layout: "list",
      },
      imaging: {
        title: "Imagerie",
        fields: [],
        layout: "list",
      },
      otherAssessments: {
        title: "Autres bilans",
        fields: [],
        layout: "list",
      },
      pleuralPuncture: {
        title: "Ponction pleurale",
        fields: [],
        layout: "list",
      },
      treatment: {
        title: "Traitement",
        fields: [],
        layout: "list",
      },
    },
  },
  pid: {
    sections: {
      admissionReason: {
        title: "Motif d'admission",
        fields: [],
        layout: "list",
      },
      medicalHistory: {
        title: "Antécédents médicaux",
        fields: [],
        layout: "list",
      },
      toxicHistory: {
        title: "Antécédents toxiques",
        fields: [],
        layout: "list",
      },
      familyHistory: {
        title: "Antécédents familiaux",
        fields: [],
        layout: "list",
      },
      lifestyle: {
        title: "Mode de vie",
        fields: [],
        layout: "list",
      },
      gynecoObstetricHistory: {
        title: "Antécédents gynéco-obstétricaux",
        fields: [],
        layout: "list",
      },
      generalSigns: {
        title: "Signes généraux",
        fields: [],
        layout: "list",
      },
      respiratorySymptoms: {
        title: "Symptômes respiratoires",
        fields: [],
        layout: "list",
      },
      extraRespiratorySymptoms: {
        title: "Symptômes extra-respiratoires",
        fields: [],
        layout: "list",
      },
      clinicalExam: {
        title: "Examen clinique",
        fields: [],
        layout: "grid",
      },
      complementaryExams: {
        title: "Examens complémentaires",
        fields: [],
        layout: "grid",
      },
      finalDiagnosis: {
        title: "Diagnostic final",
        fields: [],
        layout: "list",
      },
    },
  },
  pneumothorax: {
    sections: {
      consultationReason: {
        title: "Motif de consultation",
        fields: [
          "pneumothoraxConsultationReason.thoracicPain",
          "pneumothoraxConsultationReason.dyspnea",
          "pneumothoraxConsultationReason.cough",
          "pneumothoraxConsultationReason.thoracicOppression",
          "pneumothoraxConsultationReason.malaiseSyncope",
          "pneumothoraxConsultationReason.radiologicalDiscovery",
          "pneumothoraxConsultationReason.other",
          "pneumothoraxConsultationReason.otherDetails",
        ],
        layout: "grid",
      },
      medicalHistory: {
        title: "Antécédents médicaux",
        fields: [
          "pneumothoraxMedicalHistory.previousPneumothorax",
          "pneumothoraxMedicalHistory.previousPneumothoraxSide",
          "pneumothoraxMedicalHistory.previousPneumothoraxCount",
          "pneumothoraxMedicalHistory.previousPneumothoraxDate",
          "pneumothoraxMedicalHistory.bpcoEmphysema",
          "pneumothoraxMedicalHistory.severeAsthma",
          "pneumothoraxMedicalHistory.tuberculosis",
          "pneumothoraxMedicalHistory.pidFibrosis",
          "pneumothoraxMedicalHistory.cancers",
          "pneumothoraxMedicalHistory.cancersDetails",
          "pneumothoraxMedicalHistory.cardiopathy",
          "pneumothoraxMedicalHistory.hta",
          "pneumothoraxMedicalHistory.diabetes",
          "pneumothoraxMedicalHistory.irc",
          "pneumothoraxMedicalHistory.thoracicSurgery",
          "pneumothoraxMedicalHistory.otherPersonal",
          "pneumothoraxMedicalHistory.otherPersonalDetails",
          "pneumothoraxMedicalHistory.recentThoracicTrauma",
          "pneumothoraxMedicalHistory.mechanicalVentilation",
          "pneumothoraxMedicalHistory.cvcPleuralPuncture",
          "pneumothoraxMedicalHistory.otherRecentProcedure",
          "pneumothoraxMedicalHistory.otherRecentProcedureDetails",
          "pneumothoraxMedicalHistory.smoking",
          "pneumothoraxMedicalHistory.smokingQuantity",
          "pneumothoraxMedicalHistory.cannabisDrugs",
          "pneumothoraxMedicalHistory.longiligneMorphotype",
          "pneumothoraxMedicalHistory.recentExposure",
          "pneumothoraxMedicalHistory.allergies",
          "pneumothoraxMedicalHistory.allergiesDetails",
          "pneumothoraxMedicalHistory.chronicTreatments",
          "pneumothoraxMedicalHistory.chronicTreatmentsDetails",
        ],
        layout: "grid",
      },
      diseaseHistory: {
        title: "Histoire de la maladie",
        fields: [
          "pneumothoraxDiseaseHistory.onset",
          "pneumothoraxDiseaseHistory.onsetDateTime",
          "pneumothoraxDiseaseHistory.circumstances",
          "pneumothoraxDiseaseHistory.thoracicPain",
          "pneumothoraxDiseaseHistory.thoracicPainType",
          "pneumothoraxDiseaseHistory.thoracicPainSide",
          "pneumothoraxDiseaseHistory.dyspnea",
          "pneumothoraxDiseaseHistory.dyspneaIntensity",
          "pneumothoraxDiseaseHistory.cough",
          "pneumothoraxDiseaseHistory.hemoptysis",
          "pneumothoraxDiseaseHistory.fever",
          "pneumothoraxDiseaseHistory.associatedSigns",
          "pneumothoraxDiseaseHistory.commentsChronology",
        ],
        layout: "grid",
      },
      clinicalExam: {
        title: "Examen clinique",
        fields: [
          "pneumothoraxClinicalExam.ta",
          "pneumothoraxClinicalExam.fc",
          "pneumothoraxClinicalExam.fr",
          "pneumothoraxClinicalExam.spO2",
          "pneumothoraxClinicalExam.temp",
          "pneumothoraxClinicalExam.painEva",
          "pneumothoraxClinicalExam.respiratoryDistress",
          "pneumothoraxClinicalExam.desaturation",
          "pneumothoraxClinicalExam.hemodynamicInstability",
          "pneumothoraxClinicalExam.consciousnessAlteration",
          "pneumothoraxClinicalExam.compressivePneumothorax",
          "pneumothoraxClinicalExam.thoracicAsymmetry",
          "pneumothoraxClinicalExam.thoracicAsymmetrySide",
          "pneumothoraxClinicalExam.subcutaneousEmphysema",
          "pneumothoraxClinicalExam.trachealDeviation",
          "pneumothoraxClinicalExam.cyanosis",
          "pneumothoraxClinicalExam.tympanism",
          "pneumothoraxClinicalExam.tympanismSide",
          "pneumothoraxClinicalExam.diminishedVesicularMurmur",
          "pneumothoraxClinicalExam.diminishedVesicularMurmurSide",
          "pneumothoraxClinicalExam.associatedRales",
          "pneumothoraxClinicalExam.associatedRalesDetails",
          "pneumothoraxClinicalExam.tachycardia",
          "pneumothoraxClinicalExam.shockSigns",
          "pneumothoraxClinicalExam.otherCardiovascular",
          "pneumothoraxClinicalExam.otherCardiovascularDetails",
          "pneumothoraxClinicalExam.otherExams",
        ],
        layout: "grid",
      },
      complementaryExams: {
        title: "Examens complémentaires",
        fields: [
          "pneumothoraxComplementaryExams.chestXray",
          "pneumothoraxComplementaryExams.chestXrayReport",
          "pneumothoraxComplementaryExams.pleuralUltrasound",
          "pneumothoraxComplementaryExams.pleuralUltrasoundReport",
          "pneumothoraxComplementaryExams.thoracicCtd",
          "pneumothoraxComplementaryExams.imagingResults",
          "pneumothoraxComplementaryExams.bloodGas",
          "pneumothoraxComplementaryExams.nfs",
          "pneumothoraxComplementaryExams.crp",
          "pneumothoraxComplementaryExams.ionogram",
          "pneumothoraxComplementaryExams.hemostasis",
          "pneumothoraxComplementaryExams.bloodGroup",
        ],
        layout: "grid",
      },
      diagnosis: {
        title: "Diagnostic",
        fields: [
          "pneumothoraxDiagnosis.spontaneousPrimary",
          "pneumothoraxDiagnosis.spontaneousSecondary",
          "pneumothoraxDiagnosis.spontaneousSecondaryTerrain",
          "pneumothoraxDiagnosis.traumatic",
          "pneumothoraxDiagnosis.iatrogenic",
          "pneumothoraxDiagnosis.wellTolerated",
          "pneumothoraxDiagnosis.poorlyTolerated",
          "pneumothoraxDiagnosis.compressiveTension",
          "pneumothoraxDiagnosis.small",
          "pneumothoraxDiagnosis.medium",
          "pneumothoraxDiagnosis.large",
          "pneumothoraxDiagnosis.diagnosticConclusion",
        ],
        layout: "grid",
      },
      treatment: {
        title: "Traitement",
        fields: [
          "pneumothoraxManagement.oxygenTherapy",
          "pneumothoraxManagement.oxygenModality",
          "pneumothoraxManagement.oxygenFlow",
          "pneumothoraxManagement.analgesia",
          "pneumothoraxManagement.analgesiaDetails",
          "pneumothoraxManagement.peripheralIv",
          "pneumothoraxManagement.monitoring",
          "pneumothoraxManagement.bloodGasIndication",
          "pneumothoraxManagement.specializedAdvice",
          "pneumothoraxManagement.simpleMonitoring",
          "pneumothoraxManagement.needleAspiration",
          "pneumothoraxManagement.pleuralDrainage",
          "pneumothoraxManagement.drainageSide",
          "pneumothoraxManagement.drainageType",
          "pneumothoraxManagement.drainageSystem",
          "pneumothoraxManagement.drainageAspiration",
          "pneumothoraxManagement.drainageAspirationPressure",
          "pneumothoraxManagement.localAnesthesia",
          "pneumothoraxManagement.postProcedureXray",
          "pneumothoraxManagement.compressiveDecompression",
          "pneumothoraxManagement.persistentAirLeak",
          "pneumothoraxManagement.highRiskTerrain",
        ],
        layout: "grid",
      },
      followUp: {
        title: "Suivi",
        fields: [
          "pneumothoraxMonitoring.regularClinicalMonitoring",
          "pneumothoraxMonitoring.monitoringDetails",
          "pneumothoraxMonitoring.radiologicalControl",
          "pneumothoraxMonitoring.drainMonitoring",
          "pneumothoraxMonitoring.complications",
          "pneumothoraxMonitoring.evolutionRemarks",
        ],
        layout: "grid",
      },
      treatmentDischarge: {
        title: "Traitement et ordonnance / consignes de sortie",
        fields: [
          "pneumothoraxTreatmentDischarge.analgesic",
          "pneumothoraxTreatmentDischarge.analgesicDetails",
          "pneumothoraxTreatmentDischarge.otherTreatments",
          "pneumothoraxTreatmentDischarge.otherTreatmentsDetails",
          "pneumothoraxTreatmentDischarge.smokingCessation",
          "pneumothoraxTreatmentDischarge.hemodynamicStability",
          "pneumothoraxTreatmentDischarge.satisfactorySpO2",
          "pneumothoraxTreatmentDischarge.clinicalImprovement",
          "pneumothoraxTreatmentDischarge.satisfactoryImaging",
          "pneumothoraxTreatmentDischarge.drainRemoved",
          "pneumothoraxTreatmentDischarge.emergencyReturn",
          "pneumothoraxTreatmentDischarge.avoidHeavyEfforts",
          "pneumothoraxTreatmentDischarge.avoidEffortsDays",
          "pneumothoraxTreatmentDischarge.stopSmoking",
          "pneumothoraxTreatmentDischarge.avoidFlying",
          "pneumothoraxTreatmentDischarge.divingContraindicated",
          "pneumothoraxTreatmentDischarge.pneumologyConsultation",
          "pneumothoraxTreatmentDischarge.thoracicSurgeryConsultation",
          "pneumothoraxTreatmentDischarge.controlXray",
          "pneumothoraxTreatmentDischarge.controlXrayDate",
          "pneumothoraxTreatmentDischarge.otherInstructions",
        ],
        layout: "grid",
      },
    },
  },
  lungCancer: {
    sections: {
      consultationReason: {
        title: "Motif de consultation",
        fields: [
          "lungCancerConsultationReason.chronicCough",
          "lungCancerConsultationReason.hemoptysis",
          "lungCancerConsultationReason.dyspnea",
          "lungCancerConsultationReason.chestPain",
          "lungCancerConsultationReason.generalStateAlteration",
          "lungCancerConsultationReason.prolongedFever",
          "lungCancerConsultationReason.dysphonia",
          "lungCancerConsultationReason.fortuitousRadiologicalDiscovery",
          "lungCancerConsultationReason.extensionAssessment",
          "lungCancerConsultationReason.other",
          "lungCancerConsultationReason.otherDetails",
        ],
        layout: "grid",
      },
      medicalHistory: {
        title: "Antécédents médicaux et facteurs de risque",
        fields: [
          "lungCancerMedicalHistory.personalHistory.bpco",
          "lungCancerMedicalHistory.personalHistory.asthma",
          "lungCancerMedicalHistory.personalHistory.tuberculosis",
          "lungCancerMedicalHistory.personalHistory.pid",
          "lungCancerMedicalHistory.personalHistory.bronchiectasis",
          "lungCancerMedicalHistory.personalHistory.cardiovascularDisease",
          "lungCancerMedicalHistory.personalHistory.hta",
          "lungCancerMedicalHistory.personalHistory.diabetes",
          "lungCancerMedicalHistory.personalHistory.chronicKidneyDisease",
          "lungCancerMedicalHistory.personalHistory.liverDisease",
          "lungCancerMedicalHistory.personalHistory.cancerHistory",
          "lungCancerMedicalHistory.personalHistory.thoracicSurgery",
          "lungCancerMedicalHistory.personalHistory.thoracicRadiotherapy",
          "lungCancerMedicalHistory.personalHistory.other",
          "lungCancerMedicalHistory.riskFactors.smoking",
          "lungCancerMedicalHistory.riskFactors.packYears",
          "lungCancerMedicalHistory.riskFactors.smokingStatus",
          "lungCancerMedicalHistory.riskFactors.passiveSmoking",
          "lungCancerMedicalHistory.riskFactors.occupationalExposure",
          "lungCancerMedicalHistory.riskFactors.pollution",
          "lungCancerMedicalHistory.riskFactors.familyHistory",
          "lungCancerMedicalHistory.riskFactors.immunosuppression",
          "lungCancerMedicalHistory.allergiesTreatments.allergies",
          "lungCancerMedicalHistory.allergiesTreatments.chronicTreatments",
          "lungCancerMedicalHistory.allergiesTreatments.anticoagulantsAntiplatelets",
        ],
        layout: "grid",
      },
      diseaseHistory: {
        title: "Histoire de la maladie",
        fields: [
          "lungCancerDiseaseHistory.symptomOnsetDate",
          "lungCancerDiseaseHistory.evolution",
          "lungCancerDiseaseHistory.cough",
          "lungCancerDiseaseHistory.expectoration",
          "lungCancerDiseaseHistory.expectorationAspect",
          "lungCancerDiseaseHistory.hemoptysis",
          "lungCancerDiseaseHistory.hemoptysisType",
          "lungCancerDiseaseHistory.dyspnea",
          "lungCancerDiseaseHistory.dyspneaMmrc",
          "lungCancerDiseaseHistory.chestPain",
          "lungCancerDiseaseHistory.chestPainType",
          "lungCancerDiseaseHistory.feverSweats",
          "lungCancerDiseaseHistory.generalState",
          "lungCancerDiseaseHistory.recurrentInfections",
          "lungCancerDiseaseHistory.extensionSigns.superiorVenaCavaSyndrome",
          "lungCancerDiseaseHistory.extensionSigns.dysphonia",
          "lungCancerDiseaseHistory.extensionSigns.dysphagia",
          "lungCancerDiseaseHistory.extensionSigns.bonePain",
          "lungCancerDiseaseHistory.extensionSigns.headaches",
          "lungCancerDiseaseHistory.extensionSigns.neurologicalDisorders",
          "lungCancerDiseaseHistory.extensionSigns.convulsions",
          "lungCancerDiseaseHistory.extensionSigns.jaundice",
          "lungCancerDiseaseHistory.extensionSigns.abdominalPain",
          "lungCancerDiseaseHistory.extensionSigns.pleuralEffusion",
          "lungCancerDiseaseHistory.extensionSigns.massiveHemoptysis",
          "lungCancerDiseaseHistory.extensionSigns.commentsChronology",
        ],
        layout: "grid",
      },
      clinicalExam: {
        title: "Examen clinique",
        fields: [
          "lungCancerClinicalExam.vitalSigns.bloodPressure",
          "lungCancerClinicalExam.vitalSigns.heartRate",
          "lungCancerClinicalExam.vitalSigns.respiratoryRate",
          "lungCancerClinicalExam.vitalSigns.spO2",
          "lungCancerClinicalExam.vitalSigns.temperature",
          "lungCancerClinicalExam.vitalSigns.weight",
          "lungCancerClinicalExam.vitalSigns.height",
          "lungCancerClinicalExam.performanceStatus.ecogScore",
          "lungCancerClinicalExam.performanceStatus.markedGeneralState",
          "lungCancerClinicalExam.performanceStatus.lowBmi",
          "lungCancerClinicalExam.performanceStatus.dehydration",
          "lungCancerClinicalExam.respiratoryExam.pleuralFluidSyndrome",
          "lungCancerClinicalExam.respiratoryExam.condensationSyndrome",
          "lungCancerClinicalExam.respiratoryExam.wheezing",
          "lungCancerClinicalExam.respiratoryExam.crackles",
          "lungCancerClinicalExam.respiratoryExam.localizedDiminishedBreathSounds",
          "lungCancerClinicalExam.respiratoryExam.pleuralEffusionSigns",
          "lungCancerClinicalExam.respiratoryExam.atelectasisSigns",
          "lungCancerClinicalExam.respiratoryExam.other",
          "lungCancerClinicalExam.cardiovascularExam.rhythm",
          "lungCancerClinicalExam.cardiovascularExam.murmur",
          "lungCancerClinicalExam.cardiovascularExam.heartFailureSigns",
          "lungCancerClinicalExam.cardiovascularExam.pericardialFriction",
          "lungCancerClinicalExam.cardiovascularExam.abolishedHeartSounds",
          "lungCancerClinicalExam.cardiovascularExam.other",
          "lungCancerClinicalExam.lymphNodeExam.supraclavicularRight",
          "lungCancerClinicalExam.lymphNodeExam.supraclavicularLeft",
          "lungCancerClinicalExam.lymphNodeExam.cervical",
          "lungCancerClinicalExam.lymphNodeExam.axillary",
          "lungCancerClinicalExam.lymphNodeExam.other",
          "lungCancerClinicalExam.generalExam.hepatomegaly",
          "lungCancerClinicalExam.generalExam.bonePain",
          "lungCancerClinicalExam.generalExam.focalNeurologicalDeficit",
          "lungCancerClinicalExam.generalExam.superiorVenaCavaSyndrome",
          "lungCancerClinicalExam.generalExam.lowerLimbEdema",
          "lungCancerClinicalExam.generalExam.skinSigns",
          "lungCancerClinicalExam.generalExam.clinicalExamRemarks",
          "lungCancerClinicalExam.generalExam.otherExams",
        ],
        layout: "grid",
      },
      complementaryExams: {
        title: "Examens complémentaires",
        fields: [
          "lungCancerComplementaryExams.thoracicImaging.chestXRay",
          "lungCancerComplementaryExams.thoracicImaging.chestXRayReport",
          "lungCancerComplementaryExams.thoracicImaging.tapCt",
          "lungCancerComplementaryExams.thoracicImaging.tapCtReport",
          "lungCancerComplementaryExams.thoracicImaging.brainMri",
          "lungCancerComplementaryExams.thoracicImaging.brainMriReport",
          "lungCancerComplementaryExams.thoracicImaging.petCt",
          "lungCancerComplementaryExams.thoracicImaging.petCtReport",
          "lungCancerComplementaryExams.thoracicImaging.pleuralUltrasound",
          "lungCancerComplementaryExams.thoracicImaging.pleuralUltrasoundReport",
          "lungCancerComplementaryExams.thoracicImaging.other",
          "lungCancerComplementaryExams.endoscopyBiopsies.bronchoscopy",
          "lungCancerComplementaryExams.endoscopyBiopsies.bronchoscopyReport",
          "lungCancerComplementaryExams.endoscopyBiopsies.bronchialBiopsies",
          "lungCancerComplementaryExams.endoscopyBiopsies.bronchialBiopsiesReport",
          "lungCancerComplementaryExams.endoscopyBiopsies.balCytology",
          "lungCancerComplementaryExams.endoscopyBiopsies.balCytologyResults",
          "lungCancerComplementaryExams.endoscopyBiopsies.ebus",
          "lungCancerComplementaryExams.endoscopyBiopsies.ebusResults",
          "lungCancerComplementaryExams.endoscopyBiopsies.ctGuidedBiopsy",
          "lungCancerComplementaryExams.endoscopyBiopsies.ctGuidedBiopsyResults",
          "lungCancerComplementaryExams.endoscopyBiopsies.diagnosticPleuralPuncture",
          "lungCancerComplementaryExams.endoscopyBiopsies.diagnosticPleuralPunctureResults",
          "lungCancerComplementaryExams.endoscopyBiopsies.lymphNodeBiopsy",
          "lungCancerComplementaryExams.endoscopyBiopsies.lymphNodeBiopsyResults",
          "lungCancerComplementaryExams.pathology.histologicalType",
          "lungCancerComplementaryExams.pathology.nsclcSubtype",
          "lungCancerComplementaryExams.pathology.molecularBiology",
          "lungCancerComplementaryExams.pathology.otherMolecular",
          "lungCancerComplementaryExams.initialBiology.cbc",
          "lungCancerComplementaryExams.initialBiology.cbcResults",
          "lungCancerComplementaryExams.initialBiology.crp",
          "lungCancerComplementaryExams.initialBiology.crpResults",
          "lungCancerComplementaryExams.initialBiology.ionogramUreaCreatinine",
          "lungCancerComplementaryExams.initialBiology.ionogramUreaCreatinineResults",
          "lungCancerComplementaryExams.initialBiology.liverFunction",
          "lungCancerComplementaryExams.initialBiology.liverFunctionResults",
          "lungCancerComplementaryExams.initialBiology.calcium",
          "lungCancerComplementaryExams.initialBiology.albuminNutrition",
          "lungCancerComplementaryExams.initialBiology.hemostasis",
          "lungCancerComplementaryExams.initialBiology.hemostasisResults",
          "lungCancerComplementaryExams.initialBiology.tumorMarkers",
          "lungCancerComplementaryExams.initialBiology.tumorMarkersResults",
          "lungCancerComplementaryExams.preTherapeuticAssessment.pftSpirometry",
          "lungCancerComplementaryExams.preTherapeuticAssessment.pftSpirometryResults",
          "lungCancerComplementaryExams.preTherapeuticAssessment.dlco",
          "lungCancerComplementaryExams.preTherapeuticAssessment.dlcoResults",
          "lungCancerComplementaryExams.preTherapeuticAssessment.bloodGas",
          "lungCancerComplementaryExams.preTherapeuticAssessment.bloodGasResults",
          "lungCancerComplementaryExams.preTherapeuticAssessment.ecg",
          "lungCancerComplementaryExams.preTherapeuticAssessment.ecgResults",
          "lungCancerComplementaryExams.preTherapeuticAssessment.echocardiography",
          "lungCancerComplementaryExams.preTherapeuticAssessment.echocardiographyResults",
          "lungCancerComplementaryExams.preTherapeuticAssessment.anestheticEvaluation",
          "lungCancerComplementaryExams.preTherapeuticAssessment.anestheticEvaluationResults",
        ],
        layout: "grid",
      },
      diagnosis: {
        title: "Diagnostic",
        fields: [
          "lungCancerDiagnosis.diagnosis.suspected",
          "lungCancerDiagnosis.diagnosis.confirmed",
          "lungCancerDiagnosis.diagnosis.nsclc",
          "lungCancerDiagnosis.diagnosis.sclc",
          "lungCancerDiagnosis.diagnosis.other",
          "lungCancerDiagnosis.diagnosis.otherDetails",
          "lungCancerDiagnosis.staging.t",
          "lungCancerDiagnosis.staging.n",
          "lungCancerDiagnosis.staging.m",
          "lungCancerDiagnosis.staging.stage",
          "lungCancerDiagnosis.staging.localizedOperable",
          "lungCancerDiagnosis.staging.locallyAdvanced",
          "lungCancerDiagnosis.staging.metastatic",
          "lungCancerDiagnosis.staging.metastaticSites",
          "lungCancerDiagnosis.staging.otherSites",
          "lungCancerDiagnosis.staging.otherSitesDetails",
        ],
        layout: "grid",
      },
      treatment: {
        title: "Prise en charge",
        fields: [
          "lungCancerManagement.immediateMeasures.oxygenotherapy",
          "lungCancerManagement.immediateMeasures.analgesia",
          "lungCancerManagement.immediateMeasures.symptomaticTreatment",
          "lungCancerManagement.immediateMeasures.oncologicalEmergency",
          "lungCancerManagement.immediateMeasures.oncologicalEmergencyType",
          "lungCancerManagement.multidisciplinaryMeeting.rcpRequested",
          "lungCancerManagement.multidisciplinaryMeeting.rcpAvailable",
          "lungCancerManagement.multidisciplinaryMeeting.rcpDate",
          "lungCancerManagement.multidisciplinaryMeeting.decision",
          "lungCancerManagement.therapeuticProject.surgery",
          "lungCancerManagement.therapeuticProject.radiotherapy",
          "lungCancerManagement.therapeuticProject.chemoradiotherapy",
          "lungCancerManagement.therapeuticProject.chemotherapy",
          "lungCancerManagement.therapeuticProject.immunotherapy",
          "lungCancerManagement.therapeuticProject.targetedTherapies",
          "lungCancerManagement.therapeuticProject.palliativeCare",
          "lungCancerManagement.therapeuticProject.other",
          "lungCancerManagement.therapeuticProject.otherDetails",
        ],
        layout: "grid",
      },
      followUp: {
        title: "Surveillance évolutive",
        fields: [
          "lungCancerFollowUp.clinicalMonitoring",
          "lungCancerFollowUp.toxicityEvaluation",
          "lungCancerFollowUp.followUpImaging",
          "lungCancerFollowUp.pftFollowUp",
          "lungCancerFollowUp.nutritionalManagement",
          "lungCancerFollowUp.smokingCessation",
          "lungCancerFollowUp.vaccination",
          "lungCancerFollowUp.evolutionResponse",
          "lungCancerFollowUp.remarks",
        ],
        layout: "grid",
      },
      treatmentDischarge: {
        title: "Traitement et ordonnance / consignes de sortie",
        fields: [
          "lungCancerTreatmentDischarge.prescribedTreatment.analgesic",
          "lungCancerTreatmentDischarge.prescribedTreatment.analgesicDetails",
          "lungCancerTreatmentDischarge.prescribedTreatment.antitussive",
          "lungCancerTreatmentDischarge.prescribedTreatment.antitussiveDetails",
          "lungCancerTreatmentDischarge.prescribedTreatment.corticosteroids",
          "lungCancerTreatmentDischarge.prescribedTreatment.corticosteroidsDetails",
          "lungCancerTreatmentDischarge.prescribedTreatment.anticoagulation",
          "lungCancerTreatmentDischarge.prescribedTreatment.anticoagulationDetails",
          "lungCancerTreatmentDischarge.prescribedTreatment.other",
          "lungCancerTreatmentDischarge.prescribedTreatment.otherDetails",
          "lungCancerTreatmentDischarge.supportiveCare.painManagement",
          "lungCancerTreatmentDischarge.supportiveCare.dyspneaManagement",
          "lungCancerTreatmentDischarge.supportiveCare.nutritionalManagement",
          "lungCancerTreatmentDischarge.supportiveCare.psychosocialSupport",
          "lungCancerTreatmentDischarge.supportiveCare.palliativeCare",
          "lungCancerTreatmentDischarge.instructionsFollowUp.emergencyReturn",
          "lungCancerTreatmentDischarge.instructionsFollowUp.smokingStop",
          "lungCancerTreatmentDischarge.instructionsFollowUp.pneumologyAppointment",
          "lungCancerTreatmentDischarge.instructionsFollowUp.oncologyAppointment",
          "lungCancerTreatmentDischarge.instructionsFollowUp.radiotherapy",
          "lungCancerTreatmentDischarge.instructionsFollowUp.biologicalControl",
          "lungCancerTreatmentDischarge.instructionsFollowUp.biologicalControlDate",
          "lungCancerTreatmentDischarge.instructionsFollowUp.imagingControl",
          "lungCancerTreatmentDischarge.instructionsFollowUp.imagingControlDate",
          "lungCancerTreatmentDischarge.instructionsFollowUp.documentsDelivered",
        ],
        layout: "grid",
      },
    },
  },
};

export type PDFConfig = typeof PDF_CONFIG;
