export interface CountryCode {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
}

export const countryCodes: CountryCode[] = [
  { code: "MA", name: "Maroc", dialCode: "+212", flag: "🇲🇦" },
  { code: "FR", name: "France", dialCode: "+33", flag: "🇫🇷" },
  { code: "DZ", name: "Algérie", dialCode: "+213", flag: "🇩🇿" },
  { code: "TN", name: "Tunisie", dialCode: "+216", flag: "🇹🇳" },
  { code: "LY", name: "Libye", dialCode: "+218", flag: "🇱🇾" },
  { code: "EG", name: "Égypte", dialCode: "+20", flag: "🇪🇬" },
  { code: "ES", name: "Espagne", dialCode: "+34", flag: "🇪🇸" },
  { code: "IT", name: "Italie", dialCode: "+39", flag: "🇮🇹" },
  { code: "DE", name: "Allemagne", dialCode: "+49", flag: "🇩🇪" },
  { code: "BE", name: "Belgique", dialCode: "+32", flag: "🇧🇪" },
  { code: "CH", name: "Suisse", dialCode: "+41", flag: "🇨🇭" },
  { code: "GB", name: "Royaume-Uni", dialCode: "+44", flag: "🇬🇧" },
  { code: "US", name: "États-Unis", dialCode: "+1", flag: "🇺🇸" },
  { code: "CA", name: "Canada", dialCode: "+1", flag: "🇨🇦" },
  { code: "SA", name: "Arabie Saoudite", dialCode: "+966", flag: "🇸🇦" },
  { code: "AE", name: "Émirats Arabes Unis", dialCode: "+971", flag: "🇦🇪" },
  { code: "QA", name: "Qatar", dialCode: "+974", flag: "🇶🇦" },
  { code: "KW", name: "Koweït", dialCode: "+965", flag: "🇰🇼" },
  { code: "TR", name: "Turquie", dialCode: "+90", flag: "🇹🇷" },
  { code: "IR", name: "Iran", dialCode: "+98", flag: "🇮🇷" },
  { code: "IQ", name: "Irak", dialCode: "+964", flag: "🇮🇶" },
  { code: "JO", name: "Jordanie", dialCode: "+962", flag: "🇯🇴" },
  { code: "LB", name: "Liban", dialCode: "+961", flag: "🇱🇧" },
  { code: "SY", name: "Syrie", dialCode: "+963", flag: "🇸🇾" },
  { code: "PS", name: "Palestine", dialCode: "+970", flag: "🇵🇸" },
  { code: "IL", name: "Israël", dialCode: "+972", flag: "🇮🇱" },
  { code: "YE", name: "Yémen", dialCode: "+967", flag: "🇾🇪" },
  { code: "OM", name: "Oman", dialCode: "+968", flag: "🇴🇲" },
  { code: "BH", name: "Bahreïn", dialCode: "+973", flag: "🇧🇭" },
  { code: "MR", name: "Mauritanie", dialCode: "+222", flag: "🇲🇷" },
  { code: "SN", name: "Sénégal", dialCode: "+221", flag: "🇸🇳" },
  { code: "ML", name: "Mali", dialCode: "+223", flag: "🇲🇱" },
  { code: "BF", name: "Burkina Faso", dialCode: "+226", flag: "🇧🇫" },
  { code: "NE", name: "Niger", dialCode: "+227", flag: "🇳🇪" },
  { code: "TD", name: "Tchad", dialCode: "+235", flag: "🇹🇩" },
  { code: "CI", name: "Côte d'Ivoire", dialCode: "+225", flag: "🇨🇮" },
  { code: "CM", name: "Cameroun", dialCode: "+237", flag: "🇨🇲" },
  { code: "CD", name: "République Démocratique du Congo", dialCode: "+243", flag: "🇨🇩" },
  { code: "CG", name: "Congo", dialCode: "+242", flag: "🇨🇬" },
  { code: "GA", name: "Gabon", dialCode: "+241", flag: "🇬🇦" },
  { code: "CF", name: "Centrafrique", dialCode: "+236", flag: "🇨🇫" },
  { code: "AO", name: "Angola", dialCode: "+244", flag: "🇦🇴" },
  { code: "MG", name: "Madagascar", dialCode: "+261", flag: "🇲🇬" },
  { code: "MU", name: "Maurice", dialCode: "+230", flag: "🇲🇺" },
  { code: "RW", name: "Rwanda", dialCode: "+250", flag: "🇷🇼" },
  { code: "ET", name: "Éthiopie", dialCode: "+251", flag: "🇪🇹" },
  { code: "KE", name: "Kenya", dialCode: "+254", flag: "🇰🇪" },
  { code: "TZ", name: "Tanzanie", dialCode: "+255", flag: "🇹🇿" },
  { code: "UG", name: "Ouganda", dialCode: "+256", flag: "🇺🇬" },
  { code: "ZA", name: "Afrique du Sud", dialCode: "+27", flag: "🇿🇦" },
  { code: "NG", name: "Nigeria", dialCode: "+234", flag: "🇳🇬" },
  { code: "GH", name: "Ghana", dialCode: "+233", flag: "🇬🇭" },
  { code: "PT", name: "Portugal", dialCode: "+351", flag: "🇵🇹" },
  { code: "NL", name: "Pays-Bas", dialCode: "+31", flag: "🇳🇱" },
  { code: "AT", name: "Autriche", dialCode: "+43", flag: "🇦🇹" },
  { code: "SE", name: "Suède", dialCode: "+46", flag: "🇸🇪" },
  { code: "NO", name: "Norvège", dialCode: "+47", flag: "🇳🇴" },
  { code: "DK", name: "Danemark", dialCode: "+45", flag: "🇩🇰" },
  { code: "FI", name: "Finlande", dialCode: "+358", flag: "🇫🇮" },
  { code: "PL", name: "Pologne", dialCode: "+48", flag: "🇵🇱" },
  { code: "CZ", name: "République Tchèque", dialCode: "+420", flag: "🇨🇿" },
  { code: "HU", name: "Hongrie", dialCode: "+36", flag: "🇭🇺" },
  { code: "RO", name: "Roumanie", dialCode: "+40", flag: "🇷🇴" },
  { code: "BG", name: "Bulgarie", dialCode: "+359", flag: "🇧🇬" },
  { code: "GR", name: "Grèce", dialCode: "+30", flag: "🇬🇷" },
  { code: "RU", name: "Russie", dialCode: "+7", flag: "🇷🇺" },
  { code: "UA", name: "Ukraine", dialCode: "+380", flag: "🇺🇦" },
  { code: "BY", name: "Biélorussie", dialCode: "+375", flag: "🇧🇾" },
  { code: "KZ", name: "Kazakhstan", dialCode: "+7", flag: "🇰🇿" },
  { code: "UZ", name: "Ouzbékistan", dialCode: "+998", flag: "🇺🇿" },
  { code: "PK", name: "Pakistan", dialCode: "+92", flag: "🇵🇰" },
  { code: "IN", name: "Inde", dialCode: "+91", flag: "🇮🇳" },
  { code: "BD", name: "Bangladesh", dialCode: "+880", flag: "🇧🇩" },
  { code: "LK", name: "Sri Lanka", dialCode: "+94", flag: "🇱🇰" },
  { code: "NP", name: "Népal", dialCode: "+977", flag: "🇳🇵" },
  { code: "MM", name: "Myanmar", dialCode: "+95", flag: "🇲🇲" },
  { code: "TH", name: "Thaïlande", dialCode: "+66", flag: "🇹🇭" },
  { code: "VN", name: "Vietnam", dialCode: "+84", flag: "🇻🇳" },
  { code: "KH", name: "Cambodge", dialCode: "+855", flag: "🇰🇭" },
  { code: "LA", name: "Laos", dialCode: "+856", flag: "🇱🇦" },
  { code: "MY", name: "Malaisie", dialCode: "+60", flag: "🇲🇾" },
  { code: "SG", name: "Singapour", dialCode: "+65", flag: "🇸🇬" },
  { code: "ID", name: "Indonésie", dialCode: "+62", flag: "🇮🇩" },
  { code: "PH", name: "Philippines", dialCode: "+63", flag: "🇵🇭" },
  { code: "JP", name: "Japon", dialCode: "+81", flag: "🇯🇵" },
  { code: "KR", name: "Corée du Sud", dialCode: "+82", flag: "🇰🇷" },
  { code: "CN", name: "Chine", dialCode: "+86", flag: "🇨🇳" },
  { code: "HK", name: "Hong Kong", dialCode: "+852", flag: "🇭🇰" },
  { code: "TW", name: "Taïwan", dialCode: "+886", flag: "🇹🇼" },
  { code: "MO", name: "Macao", dialCode: "+853", flag: "🇲🇴" },
  { code: "AU", name: "Australie", dialCode: "+61", flag: "🇦🇺" },
  { code: "NZ", name: "Nouvelle-Zélande", dialCode: "+64", flag: "🇳🇿" },
  { code: "FJ", name: "Fidji", dialCode: "+679", flag: "🇫🇯" },
  { code: "BR", name: "Brésil", dialCode: "+55", flag: "🇧🇷" },
  { code: "AR", name: "Argentine", dialCode: "+54", flag: "🇦🇷" },
  { code: "MX", name: "Mexique", dialCode: "+52", flag: "🇲🇽" },
  { code: "CO", name: "Colombie", dialCode: "+57", flag: "🇨🇴" },
  { code: "PE", name: "Pérou", dialCode: "+51", flag: "🇵🇪" },
  { code: "CL", name: "Chili", dialCode: "+56", flag: "🇨🇱" },
  { code: "VE", name: "Venezuela", dialCode: "+58", flag: "🇻🇪" },
  { code: "EC", name: "Équateur", dialCode: "+593", flag: "🇪🇨" },
  { code: "BO", name: "Bolivie", dialCode: "+591", flag: "🇧🇴" },
  { code: "PY", name: "Paraguay", dialCode: "+595", flag: "🇵🇾" },
  { code: "UY", name: "Uruguay", dialCode: "+598", flag: "🇺🇾" },
  { code: "CU", name: "Cuba", dialCode: "+53", flag: "🇨🇺" },
  { code: "DO", name: "République Dominicaine", dialCode: "+1", flag: "🇩🇴" },
  { code: "HT", name: "Haïti", dialCode: "+509", flag: "🇭🇹" },
  { code: "JM", name: "Jamaïque", dialCode: "+1", flag: "🇯🇲" },
];

export const DEFAULT_COUNTRY_CODE = "+212"; // Maroc par défaut
